name: Build and test hello world

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake make g++

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: |
          sudo chmod +x ./scripts/generateoutputs.sh
          ./scripts/generateoutputs.sh
          if [ $? -ne 0 ]; then
            exit 1
          else
            exit 0
          fi
