name: Build and test hello world

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake make g++

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Run hello world
        run: |
          output=$(./build/koala ./tests/helloworld.kol)
          expected="Hello, world!"
          diff_output=$(diff -B -y <(echo "$output") <(echo "$expected"))
          if [ -n "$diff_output" ]; then
            echo "Output does not match expected output:"
            echo "$diff_output"
            exit 1
          else
            echo "Hello world passed!"
          fi

