name: Deploy Playground to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v13
      with:
        version: latest

    - name: Build Koala (wasm, js)
      run: |
        emcmake cmake -B build
        cmake --build build

    - name: Copy site files
      run: |
        mkdir site
        cp index.html site/
        cp build/koala.js build/koala.wasm site/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site

